on:
  push:
    branches:
      - 'main_ci'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build from"
        required: true
        type: string
        default: "main"

env:
  GIT_BRANCH: "${{ inputs.branch || github.ref_name }}"

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          # windows-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout vscode-glsp on ${GIT_BRANCH}
        uses: actions/checkout@v3
        with:
          ref: "${GIT_BRANCH}"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Importing package-lock.json for pnpm
        run: pnpm import

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # pnpm isn't supported by vsce so why is it the default package manager?
      - name: Fetch dependencies
        run: pnpm fetch

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies 2
        run: npm ci

      - name: Package the extension
        run: pnpm run package

      - name: Upload the VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: "*.vsix"
